# https://www.rabbitmq.com/tutorials/tutorial-six-elixir.html
# https://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReply.html

# RPC - Request/Reply pattern

# Example of RPC echo call

version: 0.1.0

workers:
  - name: rpc_server_0
    role: rpc_server
    type: rpc_echo
    settings:
      min: 1
      max: 5000
  - name: rpc_consumer_0
    role: rpc_client
    type: rpc_echo
    settings:
      # in milliseconds
      interval: 1000
